apiVersion: v1
kind: Service
metadata:
  labels:
    service: http-test
  name: http-test-service
spec:
  type: ClusterIP
  ports:
    - name: http-test-p
      port: 80
      targetPort: http-test-ep
    - name: https-test-p
      port: 443
      targetPort: http-test-ep
  selector:
    service: http-test-service
