apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildcard-host
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-cert
  requestPolicy:
    insecure:
      action: Route
      additionalPort: 8080
  selector:
    matchLabels:
      hostname: wildcard-host
